name: Deploy to GreenGeeks

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: |
          cd client
          npm install
          npm run build

      - name: Install deploy dependencies
        run: |
          cd client
          npm install ftp-deploy

      - name: Check Node availability
        run: |
          which node
          node -v

      - name: List repo contents
        run: |
          ls -la


      - name: Run FTP deploy
        env:
          FTP_HOST: ${{ secrets.FTP_HOST }}
          FTP_USERNAME: ${{ secrets.FTP_USERNAME }}
          FTP_PASSWORD: ${{ secrets.FTP_PASSWORD }}
        run: |
          cd client
            ls -la
             node ./deploy.js

